### ISSUE TITLE
DER to JSON | JSON to DER conversion

### ISSUE THREAD

**Issue by AleksandrGaysin** [impratikjaiswal/asn1Play#3]
Hello there,

I hope this message finds you well. I am writing to inquire about a way to convert DER sequences to JSON and vice versa. However, I have noticed that the sample website I was using does not allow me to select JSON as an input format. Could you please advise me on how I can achieve this? Any help would be greatly appreciated.

Thank you for your time and assistance!

**Comment by impratikjaiswal** [comment]
Hi ,

Thank you for your email.
Let me have a look. Will update here.

Mean while can you share the sample inputs.

Best Regards,
Pj

Please consider the environment before printing this email!

**Comment by AleksandrGaysin** [comment]
Hi Pj,

I appreciate the prompt response.

Please take a look at the sample input attached.
[GetEimPackageResponse_JSON.txt](https://github.com/impratikjaiswal/asn1Play/files/15277983/GetEimPackageResponse_JSON.txt)

That's what is expected to be converted to DER.

Thank you.

**Comment by impratikjaiswal** [comment]
Hi AleksandrGaysin,

Here you go..
JSON / JER will be accepted as input formats now.
Below is the execution log. 
Need to do couple of more testing before deployment.

<pre>
---------------------------------------------------------- Dev ---------------------------------------------------------
*********************** GetEimPackageResponse; ..\..\Data\UserData\GetEimPackageResponse_JSON.txt **********************
Remarks List Generated: GetEimPackageResponse; ..\..\Data\UserData\GetEimPackageResponse_JSON.txt
Info => Conversion_Mode; Asn1 Element: GetEimPackageResponse; Input Format: json; Output Format: der
Input File: ..\..\Data\UserData\GetEimPackageResponse_JSON.txt
Input Data: {
 "euiccPackageRequest": {
  "eimSignature": "80d82b20d657f8956858ca38848c337783a7c5793429b7edcc724d7d490cbc85c38408c4bd39dd756478928ce26624c0d71e8b781ef5e56cf0f1398f494385cb",
  "euiccPackageSigned": {
   "counterValue": 3,
   "eidValue": "730f11567c634e3399fbabd91a9e5726",
   "eimId": "E7BF8FF5-56BF-3881-8F9F-26EC8E63BFF7",
   "euiccPackage": {
    "psmoList": [
     {
      "disable": {
       "iccid": "8929901012345678905f"
      }
     },
     {
      "disable": {
       "iccid": "8929901012345678905f"
      }
     }
    ]
   }
  }
 }
}

Output Data: bf4f81a2bf51819e3059802445374246384646352d353642462d333838312d384639462d3236454338453633424646375a10730f11567c634e3399fbabd91a9e5726810103a01ca40c5a0a8929901012345678905fa40c5a0a8929901012345678905f5f374080d82b20d657f8956858ca38848c337783a7c5793429b7edcc724d7d490cbc85c38408c4bd39dd756478928ce26624c0d71e8b781ef5e56cf0f1398f494385cb

--------------------------------------------------------------------------------
* GetEimPackageResponse; bf4f81a2bf51819e3059802445374246384646352d353642462d333838312d384639462d323645433845363342... *
Remarks List Generated: GetEimPackageResponse; bf4f81a2bf51819e3059802445374246384646352d353642462d333838312d384639462d323645433845363342...
Info => Conversion_Mode; Asn1 Element: GetEimPackageResponse; Input Format: der; Output Format: json
Input Data: bf4f81a2bf51819e3059802445374246384646352d353642462d333838312d384639462d3236454338453633424646375a10730f11567c634e3399fbabd91a9e5726810103a01ca40c5a0a8929901012345678905fa40c5a0a8929901012345678905f5f374080d82b20d657f8956858ca38848c337783a7c5793429b7edcc724d7d490cbc85c38408c4bd39dd756478928ce26624c0d71e8b781ef5e56cf0f1398f494385cb
Output Data: {
 "euiccPackageRequest": {
  "eimSignature": "80d82b20d657f8956858ca38848c337783a7c5793429b7edcc724d7d490cbc85c38408c4bd39dd756478928ce26624c0d71e8b781ef5e56cf0f1398f494385cb",
  "euiccPackageSigned": {
   "counterValue": 3,
   "eidValue": "730f11567c634e3399fbabd91a9e5726",
   "eimId": "E7BF8FF5-56BF-3881-8F9F-26EC8E63BFF7",
   "euiccPackage": {
    "psmoList": [
     {
      "disable": {
       "iccid": "8929901012345678905f"
      }
     },
     {
      "disable": {
       "iccid": "8929901012345678905f"
      }
     }
    ]
   }
  }
 }
}

</pre>

Cheers !!!

**Comment by impratikjaiswal** [comment]
@AleksandrGaysin 

Please refer the beta release of web site here..  
https://beta.amenitypj.in/

You should be able to play with JSON/JER now

Request you to check & do provide your feedback..

**Comment by impratikjaiswal** [comment]
Dear @AleksandrGaysin ,

Closing this issue as it is live since last month.

Thank you for your contribution in making of a better product !!!

Feel free to reopen the issue if needed.

Br
Pj
