### ISSUE TITLE
Support for SGP.32 v1.1

### ISSUE THREAD

**Issue by Anatolii-Novikov-GL** [impratikjaiswal/asn1Play#5]
Hello, Dear Asn1Play Team

GSMA introduced the version of SGP.32 v1.1. Are there any plans to add support for it?

Thank you for your time and greater product!

**Comment by impratikjaiswal** [comment]
Dear Anatoli,


Thanks for your mail.

SGP 32 is already planned.
It should be available on or before end of May.

The reason behind delay is the complexity of SGP32 asn(s), as there are lot
of imports from SGP22 where as the child objects of those imported objects
are defined in SGP32.

Br
Pj

**Comment by impratikjaiswal** [comment]
Dear @Anatolii-Novikov-GL,

Sorry for the delay in timelines.

SGP.32 v1.1 is supported now (ASN1 Play v8.1.0). Web version is (ASN1 Play v8.1.0, Amenity Pj v6.0.2)

Feel free to reopen the issue if needed.

Thank you for your contribution in making of a better product !!!

Br
Pj
