### ISSUE TITLE
Json not getting parsed to Asn1

### ISSUE THREAD

**Issue by dhakadjitesh** [impratikjaiswal/asn1Play#6]
Input:
{
  "ipaEuiccDataResponse": {
    "ipaEuiccData": {
      "euiccCertificate": "",
    }
  }
}
 
Info:
Transaction Id: 1dv26jkxz33t; Mode: Conversion_Mode; Asn1 Element: IpaEuiccDataResponse; Input Format: json; Output Format: der
 

Output:
Exception Occurred; Summary: check all your inputs; Details: 'str' object has no attribute 'hex'

**Comment by impratikjaiswal** [comment]
Dear @dhakadjitesh ,

Thank you for your contribution in making of a better product !!!

Reported issue is fixed in "ASN1 Play v8.3.0 Amenity Pj v6.0.3".

Also, your input data needs correction.


```python
This is the correct structure for ipaEuiccDataResponse:

 {
 "ipaEuiccData": {
  "euiccCertificate": ""
 }
}
```

```python
This is the working Sample of ipaEuiccDataResponse:

Input:
{
 "ipaEuiccData": {
  "defaultSmdpAddress": "smdp.amenitypj.in"
 }
}

Info:
Transaction Id: y8raqhzwfhdn; Mode: Encoding_Mode; Asn1 Element: IpaEuiccDataResponse; Input Format: json; Output Format: asn1

Output Data:
ipaEuiccData : {
  defaultSmdpAddress "smdp.amenitypj.in"
}
```

Feel free to reopen the issue if needed.

Br
Pj
